.\" $Id$
.TH vmm.cfg 5 "08 Dec 2008" "Pascal Volk"
.SH NAME
vmm.cfg \- configuration file for vmm
.SH SYNOPSIS
vmm.cfg
.SH DESCRIPTION
\fBvmm\fR(1) reads configuration data from \fIvmm.cfg\fP.
.br
The configuration file is split in multiple sections. A section starts with the
section  name, enclosed in square brackets '[' and ']' (e.g. \fB[database]\fP),
followed by \'option=value' pairs (e.g. \fBhost = 127.0.0.1\fP).
.br
Whitespace around the '=' and at the end of a value is ignored.
.PP
Empty lines and lines starting with '#' or ';' will be ignored.
.PP
Each value uses one of the following data types:
.IP \(bu
.I Boolean
to indicate if something is enabled/activated (true) or disabled/deactivated
(false).
.br
Accepted values for \fBtrue\fP are: \fB1\fP, \fByes\fP, \fBtrue\fP and \fBon\fP.
.br
Accepted values for \fBfalse\fP are: \fB0\fP, \fBno\fP, \fBfalse\fP and
\fBoff\fP.
.IP \(bu
.I Int
an integer number, written without a fractional or decimal component. For
example \fB1\fP, \fB50\fP or \fB321\fP are integers.
.IP \(bu
.I String
a sequence of characters and numbers. For example '\fBword\fP', '\fBhello
world\fP' or '\fB/usr/bin/strings\fP'
.SS SEARCH ORDER
By default vmm looks for \fIvmm.cfg\fP in the following directories in the
order listed:
.RS
.PD 0
.TP
.I
/root
.TP
.I
/usr/local/etc
.TP
.I
/etc
.PD
.RE
.PP
The first match it finds will be used.
.\" -----
.SH DATABASE SECTION
The \fBdatabase\fP section is used to specify some options required to
connect to the database.
.TP
\fBhost\fP (\fIString\fP)
Hostname or IP address of the database server.
.TP
\fBuser\fP (\fIString\fP)
Name of the database user.
.TP
\fBpass\fP (\fIString\fP)
Database password
.TP
\fBname\fP (\fIString\fP)
Name of the database.
.TP
\fBExample\fP:
[database]
.br
host = localhost
.br
user = vmm
.br
pass = T~_:L4OYyl]TU?)
.br
name = mailsys
.\" -----
.SH MAILDIR SECTION
The \fBmaildir\fP section is used to specify some options for the Maildirs.
.TP
\fBname\fP (\fIString\fP)
Default name of the maildir folder in users home directory.
.TP
\fBfolders\fP (\fIString\fP)
A colon separated list of folder names, that should be created.
.br
If no folders should be created inside the Maildir, set the value of this option
to a single colon (':').
.TP
\fBmode\fP (\fIInt\fP)
Access mode for the maildir in decimal (base 10) notation. For example:
\'drwx------' -> octal 0700 -> decimal 448
.TP
\fBdiskusage\fP (\fIBoolean\fP)
Decides if the disk usage of users maildir always should be summarized and
displayed with account information.
.TP
\fBdelete\fP (\fIBoolean\fP)
Decides if the maildir should be deleted recursive when the account is deleted.
.TP
\fBExample\fP:
[maildir]
.br
name = Maildir
.br
folders = Drafts:Sent:Templates:Trash:INBOX.News
.br
mode = 448
.br
diskusage = false
.br
delete = false
.\" -----
.SH SERVICES SECTION
The \fBservices\fP section is used to specify the default restrictions for
all accounts.
.TP
\fBsmtp\fP (\fIBoolean\fP)
Decides if users can login via smtp by default. 
.TP
\fBpop3\fP (\fIBoolean\fP)
Decides if users can login via pop3 by default. 
.TP
\fBimap\fP (\fIBoolean\fP)
Decides if users can login via imap by default. 
.TP
\fBmanagesieve\fP (\fIBoolean\fP)
Decides if users can login via managesieve by default. 
.TP
\fBExample\fP:
[services]
.br
smtp = true
.br
pop3 = true
.br
imap = false
.br
managesieve = false
.\" -----
.SH DOMDIR SECTION
The \fBdomdir\fP section is used to specify options for the directories of the
domains.
.TP
\fBbase\fP (\fIString\fP)
All domain directories will be created inside this directory.
.TP
\fBmode\fP (\fIInt\fP)
Access mode for the domain directory in decimal (base 10) notation. For
example: 'drwxrwx---' -> octal 0770 -> decimal 504
.TP
\fBdelete\fP (\fIBoolean\fP)
Decides if the domain directory and all user directories inside should be
deleted when a domain is deleted.
.TP
\fBExample\fP:
[domdir]
.br
base = /srv/mail
.br
mode = 504
.br
delete = false
.\" -----
.SH BIN SECTION
The \fBbin\fP section is used to specify some paths to some binaries required
by \fBvmm\fP.
.TP
\fBdovecotpw\fP (\fIString\fP)
The absolute path to the dovecotpw binary. This binary is used to generate a
password hash, if the \fIpasswdscheme\fP is one of 'SMD5', 'SSHA', 'CRAM-MD5',
\'HMAC-MD5', 'LANMAN', 'NTLM' or 'RPA'.
.TP
\fBdu\fP (\fIString\fP)
The absolute path to \fBdu\fR(1). This binary is used to summarize the disk
usage of a maildir.
.TP
\fBpostconf\fP (\fIString\fP)
The absolute path to Postfix' \fBpostconf\fR(1).
.br
This binary is required if \fBvmm\fR(1) has to check for some Postfix settings,
e.g. virtual_alias_expansion_limit.
.TP
\fBExample\fP:
[bin]
.br
dovecotpw = /usr/sbin/dovecotpw
.br
du = /usr/bin/du
.br
postconf = /usr/sbin/postconf
.\" -----
.SH MISC SECTION
The \fBmisc\fP section is used to define miscellaneous settings.
.TP
\fBpasswdscheme\fP (\fIString\fP)
Password scheme to use (see also: dovecotpw -l)
.TP
\fBgid_mail\fP (\fIInt\fP)
Numeric group ID of group mail (mail_privileged_group from dovecot.conf)
.TP
\fBforcedel\fP (\fIBoolean\fP)
Force deletion of accounts and aliases when a domain is deleted.
.TP
\fBtransport\fP (\fIString\fP)
Default transport for domains and accounts.
.TP
\fBExample\fP:
[misc]
.br
passwdscheme = CRAM-MD5
.br
gid_mail = 8
.br
forcedel = false
.br
transport = dovecot:
.\" -----
.SH CONFIG SECTION
The \fBconfig\fP section is a internal used control section.
.TP
\fBdone\fP (\fIBoolean\fP)
This option is set to \fIfalse\fP when \fBvmm\fP is installed for the first
time. When you edit \fIvmm.cfg\fP, set this option to \fItrue\fP. This option is
also set to \fItrue\fP when you configure vmm with the command \fBvmm
configure\fP.
.br
If this option is set to \fIfalse\fP, \fBvmm\fP will start in the interactive
configurations mode.
.TP
\fBExample\fP:
[config]
.br
done = true
.\" -----
.SH FILES
vmm.cfg
.SH SEE ALSO
vmm(1), command line tool to manage email domains/accounts/aliases
.SH AUTHOR
\fBvmm\fP and its man pages were written by Pascal Volk
<\fIp.volk@veb-it.de\fP> and are licensed under the terms of the BSD License.
