# -*- coding: UTF-8 -*-
# Copyright 2007-2008 VEB IT
# See COPYING for distribution information.
# $Id$

ACCOUNT_AND_ALIAS_PRESENT = 20
ACCOUNT_EXISTS = 21
ACCOUNT_PRESENT = 22
ALIASDOMAIN_EXISTS = 23
ALIASDOMAIN_ISDOMAIN = 24
ALIASDOMAIN_NO_DOMDEST = 25
ALIAS_ADDR_DEST_IDENTICAL = 26
ALIAS_EXISTS = 27
ALIAS_MISSING_DEST = 28
ALIAS_PRESENT = 29
CONF_ERROR = 30
CONF_NOFILE = 31
CONF_NOPERM = 32
CONF_WRONGPERM = 33
DATABASE_ERROR = 34
DOMAINDIR_GROUP_MISMATCH = 35
DOMAIN_ALIAS_EXISTS = 36
DOMAIN_EXISTS = 37
DOMAIN_INVALID = 38
DOMAIN_NO_NAME = 39
DOMAIN_TOO_LONG = 40
FOUND_DOTS_IN_PATH = 41
INVALID_ADDRESS = 42
INVALID_AGUMENT = 43
INVALID_OPTION = 44
INVALID_SECTION = 45
LOCALPART_INVALID = 46
LOCALPART_TOO_LONG = 47
MAILDIR_PERM_MISMATCH = 48
MAILLOCATION_INIT = 49
NOT_EXECUTABLE = 50
NO_SUCH_ACCOUNT = 51
NO_SUCH_ALIAS = 52
NO_SUCH_ALIASDOMAIN = 53
NO_SUCH_BINARY = 54
NO_SUCH_DIRECTORY = 55
NO_SUCH_DOMAIN = 56
NO_SUCH_RELOCATED = 57
RELOCATED_ADDR_DEST_IDENTICAL = 58
RELOCATED_EXISTS = 59 
RELOCATED_MISSING_DEST = 60 
TRANSPORT_INIT = 61
UNKNOWN_MAILLOCATION_ID = 62
UNKNOWN_SERVICE = 63
UNKNOWN_TRANSPORT_ID = 64
