#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# opyright 2007-2008 VEB IT
# See COPYING for distribution information.
# $Id$

ACCOUNT_AND_ALIAS_PRESENT = 20
ACCOUNT_EXISTS = 21
ACCOUNT_PRESENT = 22
ALIAS_ADDR_DEST_IDENTICAL = 23
ALIAS_EXISTS = 24
ALIAS_MISSING_DEST = 25
ALIAS_PRESENT = 26
DATABASE_ERROR = 27
DOMAINDIR_GROUP_MISMATCH = 28
DOMAIN_EXISTS = 29
DOMAIN_INVALID = 30
DOMAIN_TOO_LONG = 31
FOUND_DOTS_IN_PATH = 32
INVALID_ADDRESS = 33
INVALID_OPTION = 34
INVALID_SECTION = 35
LOCALPART_INVALID = 36
LOCALPART_TOO_LONG = 37
MAILDIR_PERM_MISMATCH = 38
NOT_EXECUTABLE = 39
NO_SUCH_ACCOUNT = 40
NO_SUCH_ALIAS = 41
NO_SUCH_BINARY = 42
NO_SUCH_DIRECTORY = 43
NO_SUCH_DOMAIN = 44
