#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# Copyright 2007-2008 VEB IT
# See COPYING for distribution information.
# $Id$

ACCOUNT_AND_ALIAS_PRESENT = 20
ACCOUNT_EXISTS = 21
ACCOUNT_PRESENT = 22
ALIAS_ADDR_DEST_IDENTICAL = 23
ALIAS_EXISTS = 24
ALIAS_MISSING_DEST = 25
ALIAS_PRESENT = 26
CONF_ERROR = 27
CONF_NOFILE = 28
CONF_NOPERM = 29
CONF_WRONGPERM = 30
DATABASE_ERROR = 31
DOMAINDIR_GROUP_MISMATCH = 32
DOMAIN_ALIAS_EXISTS = 33
DOMAIN_EXISTS = 34
DOMAIN_INVALID = 35
DOMAIN_NO_NAME = 36
DOMAIN_TOO_LONG = 37
FOUND_DOTS_IN_PATH = 38
INVALID_ADDRESS = 39
INVALID_AGUMENT = 40
INVALID_OPTION = 41
INVALID_SECTION = 42
LOCALPART_INVALID = 43
LOCALPART_TOO_LONG = 44
MAILDIR_PERM_MISMATCH = 45
MAILLOCATION_INIT = 46
NOT_EXECUTABLE = 47
NO_SUCH_ACCOUNT = 48
NO_SUCH_ALIAS = 49
NO_SUCH_BINARY = 50
NO_SUCH_DIRECTORY = 51
NO_SUCH_DOMAIN = 52
NO_SUCH_DOMAIN_ALIAS = 53
TRANSPORT_INIT = 54
UNKNOWN_MAILLOCATION_ID = 55
UNKNOWN_SERVICE = 56
UNKNOWN_TRANSPORT_ID = 57
