.\" $Id$
.TH vmm.cfg 5 "27. Aug 2008" "Pascal Volk"
.SH NAME
vmm.cfg \- Konfigurationsdatei für vmm
.SH SYNOPSIS
/usr/local/etc/vmm.cfg
.SH BESCHREIBUNG
\fBvmm\fR(1) liest Konfigurationsparameter aus der Datei
\fI/usr/local/etc/vmm.cfg\fP.
.br
Die Konfigurationsdatei ist in mehrere Abschnitte unterteilt. Jeder Abschnitt
wird mit dem, in eckigen Klammern '[' und ']' eingefassten, Namen des Abschnitts
eingeleitet (z. B. \fB[database]\fP), gefolgt von \'Option = Wert\' Einträgen
(Z. B. \fBhost = 127.0.0.1\fP).
.br
Leerräume um das Gleichheitszeichen '=' und am Ende eine Wertes werden
ignoriert.
.PP
Leerzeilen und Zeilen, die mit einer '#' oder einem ';' anfangen, werden
ignoriert.
.PP
Jeder Wert ist von einem der folgenden Datentypen:
.IP \(bu
.I Boolean
um zu bestimmen, ob etwas eingeschaltet/aktiviert (true) oder
ausgeschaltet/deaktiviert (false) ist.
.br
Mögliche Werte für \fBtrue\fP sind: \fB1\fP, \fByes\fP, \fBtrue\fP und \fBon\fP.
.br
Mögliche Werte für \fBfalse\fP sind: \fB0\fP, \fBno\fP, \fBfalse\fP und
\fBoff\fP.
.IP \(bu
.I Int
eine Integer-Zahl, geschrieben ohne eine gebrochene oder dezimale Komponente.
.br
Beispielsweise sind \fB1\fP, \fB50\fP oder \fB321\fP Integer-Zahlen.
.IP \(bu
.I String
eine Folge von Buchstaben und Zahlen.
.br
Zum Beispiel: '\fBWort\fP', '\fBHallo Welt\fP', oder '\fB/usr/bin/strings\fP' 
.\" -----
.SH DATABASE ABSCHNITT
Der \fBdatabase\fP-Abschnitt wird verwendet, um die für den Datenbankzugriff
benötigten Optionen festzulegen.
.TP
\fBhost\fP (\fIString\fP)
Der Hostname oder die IP-Adresse des Datenbank-Servers.
.TP
\fBuser\fP (\fIString\fP)
Der Name des Datenbank-Benutzers.
.TP
\fBpass\fP (\fIString\fP)
Das Passwort des Datenbank-Benutzers
.TP
\fBname\fP (\fIString\fP)
Name der zu verwendenden Datenbank.
.TP
\fBBeispiel\fP:
[database]
.br
host = localhost
.br
user = vmm
.br
pass = T~_:L4OYyl]TU?)
.br
name = mailsys
.\" -----
.SH MAILDIR ABSCHNITT
Im \fBmaildir\fP-Abschnitt werden die für die Maildirs erforderlichen Optionen
festgelegt.
.TP
\fBname\fP (\fIString\fP)
Standard-Name des Maildir-Verzeichnisses im Verzeichnis des jeweiligen
Anwenders.
.TP
\fBfolders\fP (\fIString\fP)
Eine durch Doppelpunkten getrennte Liste mit Verzeichnisnamen, die innerhalb des
Maildirs erstellt werden sollen.
.br
Sollen innerhalb des Maildirs keine Verzeichnisse angelegt werden, ist dieser
Optionen ein einzelner Doppelpunkt (':') als Wert zuzuweisen.
.TP
\fBmode\fP (\fIInt\fP)
Zugriffsbits des Maildirs in Dezimal-Schreibweise (Basis 10).
.br
Beispiel: \'drwx------' -> oktal 0700 -> dezimal 448
.TP
\fBdiskusage\fP (\fIBoolean\fP)
Legt fest, ob die Festplattenbelegung des Maildirs jedes Mal, wenn
Konto-Informationen ausgegeben werden, ermittelt und mit ausgegeben werden
sollen.
.TP
\fBdelete\fP (\fIBoolean\fP)
Bestimmt, ob das Maildir rekursiv gelöscht werden soll, wenn ein Konto gelöscht
wird.
.TP
\fBBeispiel\fP:
[maildir]
.br
name = Maildir
.br
folders = Drafts:Sent:Templates:Trash:INBOX.News
.br
mode = 448
.br
diskusage = false
.br
delete = false
.\" -----
.SH SERVICES ABSCHNITT
Im \fBservices\fP-Abschnitt werden die Standard-Beschränkungen für alle Konten
festgelegt.
.TP
\fBsmtp\fP (\fIBoolean\fP)
Legt fest, ob sich ein Anwender standardmäßig per SMTP einloggen kann.
.TP
\fBpop3\fP (\fIBoolean\fP)
Legt fest, ob sich ein Anwender standardmäßig per POP3 einloggen kann.
.TP
\fBimap\fP (\fIBoolean\fP)
Legt fest, ob sich ein Anwender standardmäßig per IMAP einloggen kann.
.TP
\fBmanagesieve\fP (\fIBoolean\fP)
Legt fest, ob sich ein Anwender standardmäßig per MANAGESIEVE einloggen kann.
.TP
\fBBeispiel\fP:
[services]
.br
smtp = true
.br
pop3 = true
.br
imap = false
.br
managesieve = false
.\" -----
.SH DOMDIR ABSCHNITT
Im \fBdomdir\fP-Abschnitt werden die Optionen der Domain-Verzeichnisse bestimmt.
.TP
\fBbase\fP (\fIString\fP)
Alle Domain-Verzeichnisse werden unterhalb dieses Basis-Verzeichnisses angelegt.
.TP
\fBmode\fP (\fIInt\fP)
Zugriffsbits des Domain-Verzeichnisses in Dezimal-Schreibweise (Basis 10).
.br
Beispiel: 'drwxrwx---' -> oktal 0770 -> dezimal 504
.TP
\fBdelete\fP (\fIBoolean\fP)
Bestimmt, ob beim Löschen einer Domain das Verzeichnis einer Domain, inklusive
aller Anwender-Verzeichnisse, rekursiv gelöscht werden soll.
.TP
\fBBeispiel\fP:
[domdir]
.br
base = /srv/mail
.br
mode = 504
.br
delete = false
.\" -----
.SH BIN ABSCHNITT
Der \fBbin\fP-Abschnitt wird verwendet, um Pfade zu Binaries, die von \fBvmm\fP
benötigt werden, anzugeben.
.TP
\fBdovecotpw\fP (\fIString\fP)
Der absolute Pfad zum dovecotpw-Binary. Diese wird verwendet, wenn als
Passwort-Schema eines der folgenden verwendet wird: 'SMD5', 'SSHA', 'CRAM-MD5',
\'HMAC-MD5', 'LANMAN', 'NTLM' oder 'RPA'.
.TP
\fBdu\fP (\fIString\fP)
Der absolute Pfad zu \fBdu\fR(1). Dieses Binary wird verwendet, wenn die
Festplattenbelegung eines Kontos ermittelt wird.
.TP
\fBBeispiel\fP:
[bin]
.br
dovecotpw = /usr/sbin/dovecotpw
.br
du = /usr/bin/du
.\" -----
.SH MISC ABSCHNITT
Im \fBmisc\fP-Abschnitt werden verschiedene Einstellungen festgelegt.
.TP
\fBpasswdscheme\fP (\fIString\fP)
Das zu verwendende Passwort-Schema (siehe auch: dovecotpw -l)
.TP
\fBgid_mail\fP (\fIInt\fP)
Die numerische Gruppen-ID der Gruppe mail, bzw. der Gruppe aus
mail_privileged_group der Datei dovecot.conf.
.TP
\fBforcedel\fP (\fIBoolean\fP)
Legt fest, ob beim Löschen einer Domain alle vorhanden Konten und/oder Aliase,
ohne Nachfrage, gelöscht werden sollen.
.TP
\fBtransport\fP (\fIString\fP)
Der Standard-Transport aller Domains und Konten.
.TP
\fBBeispiel\fP:
[misc]
.br
passwdscheme = CRAM-MD5
.br
gid_mail = 8
.br
forcedel = false
.br
transport = dovecot:
.\" -----
.SH CONFIG ABSCHNITT
Beim \fBconfig\fP-Abschnitt handelt es sich um einen internen
Steuerungs-Abschnitt.
.TP
\fBdone\fP (\fIBoolean\fP)
Diese Option hat den den Wert \fIfalse\fP, wenn vmm zum ersten Mal installiert
wurde. Wenn die Datei \fIvmm.cfg\fP von Hand editiert wird, weisen Sie dieser
Option abschließend den Wert \fItrue\fP zu.
.br
Wird die Konfiguration über das Kommando \fBvmm configure\fP angepasst, wird der
Wert dieser Option automatisch auf \fItrue\fP gesetzt.
.br
Sollte diese Option den Wert \fIfalse\fP zugewiesen haben, so startet \fBvmm\fP
beim nächsten Aufruf im interaktiven Konfigurations-Modus.
.TP
\fBBeispiel\fP:
[config]
.br
done = true
.\" -----
.SH DATEIEN
/usr/local/etc/vmm.cfg
.SH SIEHE AUCH
vmm(1), Programm für die Kommandozeile, um E-Mail-Domains, -Konten und -Aliase
zu verwalten.
.SH AUTOR
\fBvmm\fP und die dazugehörigen Manualseiten wurden von Pascal Volk
<\fIp.volk@veb-it.de\fP> geschrieben und sind unter den Bedingungen der BSD
Lizenz lizenziert.
